/** 联盟链 — Klook + Viator；官方预约/时刻仍为主链 */
window.AFFILIATE_DATA = {
  /** Viator 等 — 按 pages 出现在对应页面 */
  experiences: [
    {
      id: "klook_yakuzaru_day",
      partner: "klook",
      adid: "1492158",
      placement: "without_car_yakuzaru_day",
      pages: ["without-car"],
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1492158&k_site=https%3A%2F%2Fwww.klook.com%2Fzh-CN%2Factivity%2F156301-yakuzaru-sightseeing-bus-yakushima-island-full-day-tour",
      title: {
        ja: "やくざる号・屋久島周遊（1日）",
        zh: "屋久岛观光巴士「やくざる号」（全天）",
        en: "Yakuzaru sightseeing bus (full day)",
      },
      body: {
        ja: "車なしで滝・ヤクスギランドなどを巡る日本語ツアー。Klook 表示は100件以上の予約。",
        zh: "不自驾串联瀑布、屋久杉 Land 等景点；日语导览。Klook 页面显示 100+ 人预订。",
        en: "See waterfalls and Yakusugi Land without driving. Japanese-guided; Klook shows 100+ bookings.",
      },
      cta: { ja: "内容・空席を見る", zh: "查看行程与余位", en: "Check itinerary & dates" },
    },
    {
      id: "viator_jetfoil_day",
      requiresRouteId: "shiratani",
      partner: "viator",
      productCode: "43454P739",
      placement: "viator_jetfoil_day",
      pages: ["trekking", "without-car"],
      tags: ["day_trip", "jetfoil", "trekking", "shiratani"],
      url: "https://www.viator.com/tours/Kagoshima-Prefecture/Day-trip-to-Yakushima-by-high-speed-Jetfoil-Toppy-from-Kagoshima/d50190-43454P739?pid=P00307180&mcid=42383&medium=link&medium_version=selector",
      title: {
        ja: "鹿児島発・高速船屋久島日帰り（白谷雲水峡ハイキング）",
        zh: "鹿儿岛出发 · 高速船屋久岛一日游（白谷徒步）",
        en: "Yakushima day trip by jetfoil from Kagoshima (Shiratani hike)",
      },
      body: {
        ja: "トッピー往復＋英語ガイド付き森林ハイキング。時間がない方向けの定番コース。",
        zh: "含 Toppy 往返高速船与英文向导森林徒步，适合时间紧的屋久岛一日游。",
        en: "Round-trip Toppy jetfoil plus guided Shiratani forest hike — classic day tour.",
      },
      cta: { ja: "Viator で見る", zh: "在 Viator 查看", en: "View on Viator" },
    },
    {
      id: "viator_private_sights",
      partner: "viator",
      productCode: "43454P373",
      placement: "viator_private_sights",
      pages: ["without-car"],
      tags: ["day_trip", "sightseeing", "private"],
      url: "https://www.viator.com/tours/Kagoshima-Prefecture/Yakushima-Private-Island-Sights-Tour-with-ENGLISH-Speaking-Guide/d50190-43454P373?pid=P00307180&mcid=42383&medium=link&medium_version=selector",
      title: {
        ja: "屋久島プライベート島内観光（英語ガイド）",
        zh: "屋久岛私人环岛观光（英文向导）",
        en: "Private Yakushima sights tour (English guide)",
      },
      body: {
        ja: "永田いなか浜・大川の滝など。貸切で柔軟な島内体験。",
        zh: "永田海滩、大川瀑布等景点，私人团灵活安排当地体验。",
        en: "Nagata beach, Ohko Falls & more — flexible private island tour.",
      },
      cta: { ja: "Viator で見る", zh: "在 Viator 查看", en: "View on Viator" },
    },
    {
      id: "viator_snorkel_turtle",
      partner: "viator",
      productCode: "306889P1",
      placement: "viator_snorkel_turtle",
      pages: ["without-car"],
      compact: true,
      tags: ["snorkeling", "marine", "turtle", "family", "day_trip"],
      url: "https://www.viator.com/tours/Kagoshima-Prefecture/%E5%B1%8B%E4%B9%85%E5%B3%B6-%E3%82%B7%E3%83%A5%E3%83%8E%E3%82%B1%E3%83%AA%E3%83%B3%E3%82%AF-%E6%86%A7%E3%82%8C%E3%81%AE%E3%82%A6%E3%83%9F%E3%82%AB%E3%83%A1%E3%81%AB%E4%BC%9A%E3%81%84%E3%81%9F%E3%81%84-%E3%82%A6%E3%83%9F%E3%82%AB%E3%83%A1%E3%81%A8%E6%B3%B3%E3%81%8E%E3%82%B7%E3%83%A5%E3%83%8E%E3%82%B1%E3%83%AA%E3%83%B3%E3%82%AF%E3%83%84%E3%82%A2-3%E6%99%82%E9%96%93/d50190-306889P1?pid=P00307180&mcid=42383&medium=link&medium_version=selector",
      title: {
        ja: "ウミガメシュノーケリング（約3時間）",
        zh: "与海龟同游浮潜体验（约 3 小时）",
        en: "Sea turtle snorkeling tour (~3 hr)",
      },
      body: {
        ja: "初心者向け。水中動画付き。遭遇は海況次第（保証なし）。",
        zh: "适合初学者，含水下视频；能否遇到海龟视海况而定。",
        en: "Beginner-friendly with underwater video; turtle sightings depend on conditions.",
      },
      cta: { ja: "Viator で見る", zh: "在 Viator 查看", en: "View on Viator" },
    },
  ],
  items: {
    jetfoil: {
      partner: "klook",
      adid: "1492155",
      placement: "ferry_jetfoil",
      hint: {
        ja: "バウチャーは事前に印刷。往復は往路・復路を別々に選び、宮之浦／安房の港と確認書の便をご確認ください。リンク経由の予約で当サイトに紹介料が入る場合があります。",
        zh: "请提前打印凭证。往返需分别选择去程和返程套餐，注意宫之浦／安房港；班次以确认单为准。通过链接预订，本站可能获得佣金。",
        en: "Print your voucher in advance. For a return trip, select both outbound and inbound packages; check Miyanoura/Anbo port and confirmed sailings. We may earn a commission from bookings through this link.",
      },
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1492155&k_site=https%3A%2F%2Fwww.klook.com%2Fzh-CN%2Factivity%2F161058-round-trip-ticket-for-high-speed-jetfoil-toppy-or-rocket-to-yakushima",
      image: "/images/affiliate/jetfoil-klook.png",
      cta: {
        ja: "Klook で船券を見る",
        zh: "在 Klook 查看船票",
        en: "View tickets on Klook",
      },
    },
    hiking: {
      partner: "klook",
      adid: "1316225",
      placement: "trekking_jomon",
      affectedRouteId: "shiratani",
      closedHint: {
        ja: "白谷雲水峡コースは現在通行止めです。縄文杉・ヤクスギランドなど他のプランも、予約前に催行日と行程を確認してください。",
        zh: "白谷云水峡路线目前封闭。选择绳文杉、屋久杉 Land 等其他套餐前，也请在预订页核对日期和具体路线。",
        en: "The Shiratani route is currently closed. Check dates and itineraries before choosing another package, such as Jomon Sugi or Yakusugi Land.",
      },
      image: "/images/affiliate/hiking-klook.png",
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1316225&k_site=https%3A%2F%2Fwww.klook.com%2Fzh-CN%2Factivity%2F150846-yakushima-hiking-tour",
      title: {
        ja: "屋久島ガイド付きハイキング（コース選択）",
        zh: "屋久岛向导徒步（多路线套餐）",
        en: "Guided Yakushima hike (choose a route)",
      },
      body: {
        ja: "最大6名の少人数ツアー。登山用品は事前リクエストで無料レンタル可。コース・送迎条件は予約ページで確認。",
        zh: "最多 6 人的小团；可提前申请免费租用徒步装备。请在预订页核对所选路线和接送条件。",
        en: "Groups of up to 6; hiking gear is free to rent on request. Check your selected route and pickup terms on the booking page.",
      },
      cta: {
        ja: "Klook で見る",
        zh: "在 Klook 查看",
        en: "View on Klook",
      },
    },
    destYakushima: {
      partner: "klook",
      adid: "1316230",
      placement: "dest_yakushima",
      pages: ["trekking", "without-car"],
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1316230&k_site=https%3A%2F%2Fwww.klook.com%2Fzh-CN%2Fdestination%2Fp60271491-yakushima%2F",
      label: {
        ja: "Klook 屋久島ページを見る",
        zh: "查看 Klook 屋久岛专区",
        en: "Browse Yakushima on Klook",
      },
    },
    destKagoshima: {
      partner: "klook",
      adid: "1492153",
      placement: "dest_kagoshima",
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1492153&k_site=https%3A%2F%2Fwww.klook.com%2Fen-US%2Fdestination%2Fc21043%2F",
      label: {
        ja: "Klook 鹿児島ページを見る",
        zh: "查看 Klook 鹿儿岛专区",
        en: "Browse Kagoshima on Klook",
      },
    },
    jrKyushu: {
      partner: "klook",
      adid: "1492182",
      placement: "jr_kyushu",
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1492182&k_site=https%3A%2F%2Fwww.klook.com%2Fzh-CN%2Factivity%2F2371-jr-kyushu-jr-pass",
      label: {
        ja: "JR 九州パス（鹿児島まで）",
        zh: "九州 JR Pass（到鹿儿岛）",
        en: "JR Kyushu Pass (to Kagoshima)",
      },
      note: {
        ja: "九州各地を鉄道で回る場合",
        zh: "经九州多地火车到鹿儿岛时",
        en: "If touring Kyushu by train before the island",
      },
    },
    senganEn: {
      partner: "klook",
      adid: "1492169",
      placement: "kagoshima_sengan_en",
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1492169&k_site=https%3A%2F%2Fwww.klook.com%2Fzh-CN%2Factivity%2F38419-sengan-en-garden-ticket-kagoshima",
      label: {
        ja: "仙巌園の入場券",
        zh: "仙巖園门票",
        en: "Sengan-en admission",
      },
      note: {
        ja: "鹿児島で半日過ごすなら。Klook 表示は1万件以上の予約",
        zh: "在鹿儿岛多留半天时；Klook 页面显示 1 万+ 人预订",
        en: "For extra time in Kagoshima; Klook shows 10K+ bookings",
      },
    },
    samanaHotel: {
      partner: "klook",
      adid: "1492165",
      placement: "without_car_samana_hotel",
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1492165&k_site=https%3A%2F%2Fwww.klook.com%2Fzh-CN%2Fhotels%2Fdetail%2F137390-samana-hotel-yakushima%2F",
      label: {
        ja: "samana hotel Yakushima",
        zh: "samana hotel Yakushima",
        en: "samana hotel Yakushima",
      },
      note: {
        ja: "尾之間エリア・温泉と海景色。バス停名は「samana hotel Yakushima」",
        zh: "尾之间区域，温泉与海景；本站有同名公交站",
        en: "Onoaida area, hot spring and sea views; a same-name bus stop is in our timetable",
      },
    },
    iwasakiHotel: {
      partner: "klook",
      adid: "1492166",
      placement: "without_car_iwasaki_hotel",
      url: "https://affiliate.klook.com/redirect?aid=125410&aff_adid=1492166&k_site=https%3A%2F%2Fwww.klook.com%2Fzh-CN%2Fhotels%2Fdetail%2F560390-yakushima-iwasaki-hotel%2F",
      label: {
        ja: "屋久島いわさきホテル",
        zh: "屋久岛岩崎酒店",
        en: "Yakushima Iwasaki Hotel",
      },
      note: {
        ja: "尾之間エリア・山側の滞在。バス停名は「いわさきホテル」",
        zh: "尾之间区域、山景住宿；本站有“岩崎酒店”公交站",
        en: "Onoaida area, mountain setting; Iwasaki Hotel stop is in our timetable",
      },
    },
  },
  blocks: {
    affiliateDisclosure: {
      ja: "日付・空席・料金は各予約ページで確認してください。リンク経由の予約で当サイトに紹介料が入る場合があります。",
      zh: "请在预订页确认日期、余位和价格。通过链接预订，本站可能获得佣金。",
      en: "Check dates, availability and prices on the booking page. We may earn a commission from bookings through these links.",
    },
    experiencesTitle: {
      ja: "屋久島の現地体験・日帰りツアー",
      zh: "屋久岛当地体验 · 一日游",
      en: "Yakushima tours & local experiences",
    },
    experiencesLead: {
      ja: "車なしで巡る周遊バスと英語ガイド付き貸切ツアー。路線バスの時刻は本サイト、予約条件は各販売ページで確認してください。",
      zh: "不自驾看岛上的两种方式：日语观光巴士或英文私人团。定线公交查本站，预订条件看商品页。",
      en: "Two ways to explore without driving: a Japanese-guided sightseeing bus or an English-guided private tour. Check local bus times here and booking terms on each product page.",
    },
    trekkingExperiencesLead: {
      ja: "ガイド付き登山ツアー。希望コースと当日の道路状況を確認してください。",
      zh: "向导徒步套餐；请先核对所选路线和当天道路状态。",
      en: "Guided hiking options; check the chosen route and current road status first.",
    },
    islandBookingTitle: {
      ja: "屋久島での体験・船券",
      zh: "屋久岛活动与船票",
      en: "On Yakushima: activities & ferry tickets",
    },
    gatewayBookingTitle: {
      ja: "鹿児島での滞在・九州の移動",
      zh: "鹿儿岛停留与九州接驳",
      en: "Kagoshima stay & Kyushu rail",
    },
    moreExperiences: {
      ja: "ほかの屋久島体験",
      zh: "其他屋久岛体验",
      en: "More Yakushima experiences",
    },
    lodgingSummary: {
      ja: "バス停から選ぶ屋久島の宿",
      zh: "按公交站选屋久岛住宿",
      en: "Yakushima stays near bus stops",
    },
    lodgingLead: {
      ja: "尾之間の2軒。宿のページで希望日を選び、バスは本サイトの時刻表で確認してください。紹介料が入る場合があります。",
      zh: "两家位于尾之间区域；酒店页自行选入住日，公交班次请查本站时刻表。通过链接预订，本站可能获得佣金。",
      en: "Two Onoaida-area stays. Choose your dates on the hotel page and check buses here. We may earn a commission.",
    },
    experiencesStatsNote: {
      ja: "評価・件数は Viator 表示（{date} 時点）",
      zh: "评分与评价数来自 Viator（截至 {date}）",
      en: "Rating & review count from Viator (as of {date})",
    },
    ferryBottomSummary: {
      ja: "屋久島・鹿児島の予約サイト",
      zh: "屋久岛与鹿儿岛预订入口",
      en: "Yakushima & Kagoshima booking links",
    },
    ferryBottomLead: {
      ja: "第三者の予約サイトです。島内に JR はありません。時刻・運賃は上記公式情報を優先し、リンク経由の予約で当サイトに紹介料が入る場合があります。",
      zh: "以下为第三方预订链接；岛上无 JR。船班时刻与票价请以上方官方信息为准。通过链接预订，本站可能获得佣金。",
      en: "Third-party booking links. No JR on the island; use official timetables above. We may earn a commission from bookings through these links.",
    },
  },
};
