/** 登山コース参考 — 出典: 屋久島観光協会 https://yakukan.jp/trekking/ */
window.TREKKING_DATA = {
  updated: "2026-05-29",
  sourceUrl: "https://yakukan.jp/trekking/",
  intro: {
    ja: "屋久島観光協会の代表的トレッキングコースを参考値として掲載。",
    zh: "摘自屋久岛观光协会代表性徒步路线，难度与用时仅供参考。",
    en: "Reference trekking courses from the Yakushima tourism association.",
  },
  seasonTitle: {
    ja: "登山シーズン",
    zh: "登山季节",
    en: "Trekking season",
  },
  seasonLead: {
    ja: "春〜秋がベスト。梅雨は雨量多め。12〜2月の山岳は積雪で危険 — 初心者は避けてください。",
    zh: "春秋最佳；梅雨降雨多。12–2 月山区有积雪，新手勿入。",
    en: "Spring–autumn is best; rainy season is wet. Dec–Feb snow in the mountains — not for beginners.",
  },
  seasons: [
    {
      title: { ja: "春", zh: "春", en: "Spring" },
      items: [
        { ja: "太鼓岩からの山桜", zh: "太鼓岩一带山樱", en: "Cherry blossoms near Taiko-iwa" },
        { ja: "ヤクシマシャクナゲなど固有種", zh: "屋久杜鹃等特有植物", en: "Endemic rhododendron & violets" },
      ],
    },
    {
      title: { ja: "夏", zh: "夏", en: "Summer" },
      items: [
        { ja: "梅雨（5月下旬〜7月中旬）", zh: "梅雨（5 月下旬–7 月中旬）", en: "Rainy season (late May–mid Jul)" },
        { ja: "高海拔林带凉爽", zh: "高海拔林带较凉爽", en: "Cooler forest belts at altitude" },
      ],
    },
    {
      title: { ja: "秋", zh: "秋", en: "Autumn" },
      items: [
        { ja: "高山植物（イッスンキンカ等）", zh: "高山植物", en: "Alpine plants" },
        { ja: "绿与红叶对比", zh: "绿意与红叶", en: "Green vs autumn foliage" },
      ],
    },
    {
      title: { ja: "冬", zh: "冬", en: "Winter" },
      items: [
        { ja: "奥岳は雪山", zh: "内山积雪", en: "Inner peaks under snow" },
        { ja: "「日本の縮図」を体感", zh: "可体会「日本缩影」", en: "Microcosm of Japan’s climates" },
      ],
    },
  ],
  coursesTitle: {
    ja: "トレッキングコース",
    zh: "徒步路线推荐",
    en: "Trekking courses",
  },
  labels: {
    difficulty: { ja: "難易度", zh: "难度", en: "Difficulty" },
    fitness: { ja: "体力度", zh: "体能", en: "Fitness" },
    distance: { ja: "距離", zh: "距离", en: "Distance" },
    duration: { ja: "所要時間", zh: "用时", en: "Time" },
    elevation: { ja: "標高差", zh: "爬升", en: "Elevation" },
    yakukan: { ja: "観光協会", zh: "观光协会", en: "Tourism assoc." },
    yamap: { ja: "YAMAP", zh: "YAMAP", en: "YAMAP" },
    allTrails: { ja: "AllTrails", zh: "AllTrails", en: "AllTrails" },
  },
  courses: [
    {
      id: "jomon_sugi",
      title: { ja: "縄文杉トレッキング", zh: "绳文杉徒步", en: "Jomon Sugi trek" },
      difficulty: 4,
      fitness: 4,
      distance: { ja: "約22km", zh: "约 22 km", en: "~22 km" },
      duration: { ja: "9〜10時間", zh: "9–10 小时", en: "9–10 hr" },
      elevation: { ja: "610m", zh: "610 m", en: "610 m" },
      yakukanUrl: "https://yakukan.jp/feature/jomonsugi-course.html",
      yamapUrl: "https://yamap.com/model-courses/25891",
    },
    {
      id: "taikoiwa",
      title: { ja: "太鼓岩トレッキング", zh: "太鼓岩徒步", en: "Taiko-iwa trek" },
      difficulty: 3,
      fitness: 3,
      distance: { ja: "約5.5km", zh: "约 5.5 km", en: "~5.5 km" },
      duration: { ja: "4〜5時間", zh: "4–5 小时", en: "4–5 hr" },
      elevation: { ja: "430m", zh: "430 m", en: "430 m" },
      yakukanUrl: "https://yakukan.jp/feature/taikoiwa-course.html",
      yamapUrl: "https://yamap.com/model-courses/26038",
    },
    {
      id: "tachudake",
      title: { ja: "太忠岳トレッキング", zh: "太忠岳徒步", en: "Mt. Tachu trek" },
      difficulty: 3,
      fitness: 2,
      distance: { ja: "約7km", zh: "约 7 km", en: "~7 km" },
      duration: { ja: "6〜7時間", zh: "6–7 小时", en: "6–7 hr" },
      elevation: { ja: "497m", zh: "497 m", en: "497 m" },
      yakukanUrl: "https://yakukan.jp/feature/tachudake-course.html",
      allTrailsUrl: "https://www.alltrails.com/trail/japan/kagoshima--2/mount-tachu",
    },
    {
      id: "kuromidake",
      title: { ja: "黒味岳トレッキング", zh: "黑味岳徒步", en: "Mt. Kuromi trek" },
      difficulty: 3,
      fitness: 3,
      distance: { ja: "約9km", zh: "约 9 km", en: "~9 km" },
      duration: { ja: "6〜7時間", zh: "6–7 小时", en: "6–7 hr" },
      elevation: { ja: "466m", zh: "466 m", en: "466 m" },
      yakukanUrl: "https://yakukan.jp/feature/kuromidake-course.html",
      yamapUrl: "https://yamap.com/model-courses/20298",
    },
    {
      id: "janokuchi",
      title: { ja: "蛇之口滝トレッキング", zh: "蛇之口瀑布徒步", en: "Janokuchi Falls trek" },
      difficulty: 3,
      fitness: 2,
      distance: { ja: "約7km", zh: "约 7 km", en: "~7 km" },
      duration: { ja: "3〜4時間", zh: "3–4 小时", en: "3–4 hr" },
      elevation: { ja: "410m", zh: "410 m", en: "410 m" },
      yakukanUrl: "https://yakukan.jp/feature/janokuchitaki-course.html",
      yamapUrl: "https://yamap.com/model-courses/43825",
    },
    {
      id: "miyanouradake",
      title: { ja: "宮之浦岳トレッキング", zh: "宫之浦岳徒步", en: "Mt. Miyanoura trek" },
      difficulty: 5,
      fitness: 5,
      distance: { ja: "約14km", zh: "约 14 km", en: "~14 km" },
      duration: { ja: "10〜11時間", zh: "10–11 小时", en: "10–11 hr" },
      elevation: { ja: "571m", zh: "571 m", en: "571 m" },
      yakukanUrl: "https://yakukan.jp/feature/miyanouradake-course.html",
      yamapUrl: "https://yamap.com/model-courses/1613",
    },
    {
      id: "mocchomudake",
      title: { ja: "モッチョム岳トレッキング", zh: "本富岳（モッチョム岳）徒步", en: "Mt. Mocchomu trek" },
      difficulty: 4,
      fitness: 3,
      distance: { ja: "約5.5km", zh: "约 5.5 km", en: "~5.5 km" },
      duration: { ja: "7〜9時間", zh: "7–9 小时", en: "7–9 hr" },
      elevation: { ja: "667m", zh: "667 m", en: "667 m" },
      yakukanUrl: "https://yakukan.jp/feature/mocchomudake-course.html",
      allTrailsUrl: "https://www.alltrails.com/trail/japan/kagoshima--2/mount-mocchomu-dake",
    },
    {
      id: "aikodake",
      title: { ja: "愛子岳トレッキング", zh: "爱子岳徒步", en: "Mt. Aiko trek" },
      difficulty: 4,
      fitness: 2,
      distance: { ja: "約8km", zh: "约 8 km", en: "~8 km" },
      duration: { ja: "6〜7時間", zh: "6–7 小时", en: "6–7 hr" },
      elevation: { ja: "1,058m", zh: "1,058 m", en: "1,058 m" },
      yakukanUrl: "https://yakukan.jp/feature/aikodake-course.html",
      allTrailsUrl: "https://www.alltrails.com/trail/japan/kagoshima--2/mount-aikodake",
    },
  ],
  resourcesTitle: {
    ja: "公式資料（PDF）",
    zh: "官方资料（PDF）",
    en: "Official PDFs",
  },
  resources: [
    {
      label: {
        ja: "屋久島登山マップ・コース情報",
        zh: "屋久岛登山地图·路线补充",
        en: "Yakushima trekking map & courses",
      },
      url: "https://yakukan.jp/wp-content/uploads/2025/06/20250609084458.pdf",
      note: { ja: "2025/6 更新", zh: "2025/6 更新", en: "Updated 2025-06" },
    },
  ],
  disclaimer: {
    ja: "難易度・所要時間は観光協会の参考値です。装備・登山届・天候は必ず公式情報で確認してください。当サイトは交通時刻の補助であり、登山ガイドではありません。",
    zh: "难度与用时摘自观光协会，装备、登山登记与天气请以官方为准。本站仅辅助查交通，非登山攻略。",
    en: "Difficulty and times are tourism-association references only. Check official sources for gear, permits, and weather. This site helps with transport—not trekking guidance.",
  },
};
