#!/usr/bin/env python3
"""Build shared operational notices; planned timetables remain in their manifests."""
import json
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def build_data():
    status = json.loads((ROOT / 'sources/transport-status.json').read_text())
    manifest = json.loads((ROOT / 'sources/manifest.json').read_text())
    status['timetable'] = {key: manifest[key] for key in ('revision', 'validFrom', 'validTo')}
    status['timetable']['sourceUrl'] = manifest['sources']['notice']['url']
    status['pdfAssets'] = {}
    for source in manifest['sources'].values():
        file = source.get('file')
        if not file or not file.endswith('.pdf'):
            continue
        path = ROOT / file
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if source.get('sha256') != digest:
            raise ValueError(f'Unverified PDF checksum: {file}')
        import fitz
        with fitz.open(path) as doc:
            previews = []
            for i, page in enumerate(doc):
                target = f'assets/pdf-preview/{path.stem}-{digest[:8]}-{i+1}.jpg'
                pix = page.get_pixmap(matrix=fitz.Matrix(2, 2))
                if not (ROOT / target).exists():
                    pix.save(ROOT / target)
                previews.append({'url': '/' + target, 'width': pix.width, 'height': pix.height})
        status['pdfAssets'][source['url']] = {'mirror': '/' + file, 'sha256': digest, 'previews': previews}
    return status


if __name__ == '__main__':
    (ROOT / 'transport-data.js').write_text(
        '/** Generated by scripts/build_transport_data.py; edit sources only. */\n'
        + 'window.TRANSPORT_DATA = ' + json.dumps(build_data(), ensure_ascii=False, indent=2) + ';\n')
