#!/usr/bin/env python3
"""Resolve public references from the authoritative dataset manifests."""
import argparse
import copy
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def build_data():
    manifests={name:json.loads((ROOT / path).read_text()) for name,path in [('bus','sources/manifest.json'),('access','sources/access-manifest.json')]}
    data=json.loads((ROOT/'sources/references.json').read_text())
    data['intro']={
      'ja':'時刻表・運賃・運休は各資料の適用日と確認日をご覧ください。出発前に公式発表を再確認してください。',
      'zh':'时刻表、票价与停运信息分别标注生效及核查日期。出行前请再核对官方公告。',
      'en':'Timetables, fares and notices have their own effective and checked dates. Recheck official announcements before travel.'}
    for group in data['sourceGroups']:
      for item in group['items']:
        ref=item.get('sourceRef')
        if not ref: continue
        domain,key=ref.split(':');src=manifests[domain]['sources'][key]
        item['url']=src['url']
        rev=src.get('revision');checked=src.get('checkedAt')
        if rev or checked:
          item['note']={lang:' · '.join(x for x in [f'{labels[0]} {rev}' if rev else '',f'{labels[1]} {checked}' if checked else ''] if x) for lang,labels in {'ja':('改定','確認'),'zh':('改订','核查'),'en':('Revised','Checked')}.items()}
    return data

def content(): return '/** Generated by scripts/build_sources_data.py; edit sources/references.json + manifests. */\nwindow.SOURCES_DATA = '+json.dumps(build_data(),ensure_ascii=False,indent=2)+';\n'
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args();out=ROOT/'sources-data.js'
    if a.check:
      if out.read_text()!=content(): raise SystemExit('sources-data.js differs from canonical sources; rebuild')
    else: out.write_text(content())
